name: Download Food Records

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
    inputs:
      description:
        description: 'Description of the manual run'
        required: false
        default: 'Manual download of food records'

jobs:
  download-food-records:
    name: Download and Display Food Records
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: make install
        
    - name: Download and display food records
      run: |
        echo "🚀 Starting food records download..."
        make run
        echo "✅ Food records download completed!"
        
    - name: Upload first record as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: first-food-record
        path: first_record.json
        retention-days: 30
        
    - name: Upload run summary
      if: always()
      run: |
        echo "## 🍕 Food Records Download Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Status**: Completed successfully" >> $GITHUB_STEP_SUMMARY
        echo "📊 **Records**: 5 food product records downloaded and displayed" >> $GITHUB_STEP_SUMMARY
        echo "🔗 **Source**: OpenFoodFacts dataset via Hugging Face" >> $GITHUB_STEP_SUMMARY
        echo "📁 **Artifact**: First record saved as 'first-food-record' artifact" >> $GITHUB_STEP_SUMMARY
        echo "⏰ **Timestamp**: $(date -u)" >> $GITHUB_STEP_SUMMARY